# H2 + JPA
spring.datasource.url=jdbc:h2:mem:apilab;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

app.jwt.secret=${JWT_SECRET:Xy4sA1sVJ7oE8rtn98uf0cGv3tZ1VYbqkY3mK1s8x7I=}

app.jwt.ttl-seconds=3600
app.jwt.issuer=NU-SSD-LAB
app.jwt.audience=OWASP-Students

# Expose error details (VULNERABILITY: API7-Security Misconfiguration)
server.error.include-message=always
server.error.include-stacktrace=always

logging.level.root=INFO
